services:
  tarjetas_app:
    container_name: tarjetas_ms
    image: tarjetas-ms:1.0.0
    build: ./TarjetasMS
    ports:
      - 8080:8080
    environment:
      DB_URL: ${ARG_DB_URL}
      DB_USER: ${ARG_DB_USER}
      DB_PASS: ${ARG_DB_PASS}
    depends_on:
      postgres:
        condition: service_healthy
  transacciones_app:
    container_name: transacciones_ms
    image: transacciones-ms-ms:1.0.0
    build: ./TransaccionesMS
    ports:
      - 8081:8081
    environment:
      DB_URL: ${ARG_DB_URL}
      DB_USER: ${ARG_DB_USER}
      DB_PASS: ${ARG_DB_PASS}
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:17.7
    restart: always
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${ARG_DB_USER}
      POSTGRES_PASSWORD: ${ARG_DB_PASS}
      POSTGRES_DB: ${ARG_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./pgbankinkdata:/var/lib/postgresql/data/
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${ARG_DB_USER} -d ${ARG_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10
